-- Add sales recording columns to orders table
ALTER TABLE orders ADD COLUMN order_number INTEGER;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
    CREATE TYPE order_status AS ENUM ('completed', 'voided', 'refunded');
  END IF;
END
$$;

ALTER TABLE orders ADD COLUMN status order_status NOT NULL DEFAULT 'completed';

ALTER TABLE orders ADD COLUMN discount_type_id UUID REFERENCES discount_types(id);
ALTER TABLE orders ADD COLUMN discount_method VARCHAR(10) CHECK (discount_method IN ('percentage', 'fixed'));
ALTER TABLE orders ADD COLUMN discount_value DECIMAL(10,2);
ALTER TABLE orders ADD COLUMN discount_amount DECIMAL(10,2);

ALTER TABLE orders ADD COLUMN tip_amount DECIMAL(10,2);
ALTER TABLE orders ADD COLUMN tip_recipient_id UUID REFERENCES auth.users(id);

ALTER TABLE orders ADD COLUMN refund_amount DECIMAL(10,2);
ALTER TABLE orders ADD COLUMN refund_reason_id UUID REFERENCES void_refund_reasons(id);
ALTER TABLE orders ADD COLUMN refunded_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN refunded_by UUID REFERENCES auth.users(id);

ALTER TABLE orders ADD COLUMN void_reason_id UUID REFERENCES void_refund_reasons(id);
ALTER TABLE orders ADD COLUMN voided_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN voided_by UUID REFERENCES auth.users(id);

CREATE INDEX IF NOT EXISTS idx_orders_shop_status ON orders(shop_id, status);
CREATE INDEX IF NOT EXISTS idx_orders_shop_order_number ON orders(shop_id, order_number);
CREATE INDEX IF NOT EXISTS idx_orders_shop_date ON orders(shop_id, order_date DESC);

COMMENT ON COLUMN orders.order_number IS 'Sequential order number per shop, auto-generated by trigger';
COMMENT ON COLUMN orders.status IS 'Order lifecycle: completed -> voided or refunded';
COMMENT ON COLUMN orders.discount_method IS 'percentage or fixed';
COMMENT ON COLUMN orders.discount_value IS 'Input value (e.g., 10 for 10% or $10)';
COMMENT ON COLUMN orders.discount_amount IS 'Calculated dollar amount of discount';
